Update index.js
jhipster/jhipster-dotnetcore pull request #1155
Opened 2022-10-01 21:20 UTC by vedant-z

-   Please make sure the below checklist is followed for Pull Requests.

Fixes #

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

2022-10-02 07:09 UTC, nicolas63 commented
Your code is right but you need to declare the const from this file https://github.com/jhipster/generator-jhipster/blob/main/lib/constants/priorities.cjs

Like this line https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/client/files-common.js#L22

2022-10-04 18:03 UTC, vedant-z commented
@nicolas63 Thank you for supporting and guiding me 
I know you might be frustrated by the checks failing as am I.

2022-10-05 06:11 UTC, nicolas63 requested changes

2022-10-05 06:11 UTC, nicolas63 commented on generators/app/index.js
> +    get [WRITIING_PRIORITY]() {
Typo Wriiting => Writing

2022-10-05 06:11 UTC, nicolas63 commented on generators/app/index.js
> +const constants = require('generator-jhipster/lib/constants/priorities.cjs');
correct the indentation (eslint can help you) install it with 
```
npm install eslint --global 
```
after that you can run eslint --fix .

2022-10-05 06:12 UTC, nicolas63 commented
> @nicolas63 Thank you for supporting and guiding me I know you might be frustrated by the checks failing as am I.

no worry about this, i'm here to help newcomer

2022-10-12 08:33 UTC, nicolas63 requested changes

2022-10-12 08:33 UTC, nicolas63 commented on generators/app/index.js
>      constructor(args, opts) {
register priority prefix in the constructor 

```
constructor(args, opts, features) {
        super(args, opts, { fromBlueprint: true, taskPrefix: PRIORITY_PREFIX, ...features }); // fromBlueprint variable is important
    }
```

2022-10-12 08:33 UTC, nicolas63 commented on generators/app/index.js
> +const { INITIALIZING_PRIORITY, PROMPTING_PRIORITY, CONFIGURING_PRIORITY, COMPOSING_PRIORITY, LOADING_PRIORITY, PREPARING_PRIORITY, DEFAULT_PRIORITY, WRITING_PRIORITY, POST_WRITING_PRIORITY, END_PRIOR
add priority prefix here, PRIORITY_PREFIX

2022-10-19 08:46 UTC, nicolas63 commented
@vedant-z do you need help ?

2022-10-19 08:52 UTC, vedant-z commented
I think I can't solve this issue 😥

I have done everything as said by you but still it's not passing thr checks 

What should I do now @nicolas63

2022-10-19 08:57 UTC, nicolas63 requested changes

2022-10-19 08:58 UTC, nicolas63 commented
> I think I can't solve this issue 😥
> 
> I have done everything as said by you but still it's not passing thr checks
> 
> What should I do now @nicolas63

 see the last review, it's a small problem with the constructor

2022-10-26 05:24 UTC, nicolas63 commented
Looks good to me, just rebase your branch and i merge your PR

2022-11-27 18:00 UTC, nicolas63 commented
@vedant-z any update ?

2022-11-29 15:15 UTC, vedant-z commented
Ya I will rebase and make PR

2023-10-02 19:17 UTC, closed without merging