(fix): Allow override of primary key type
jhipster/jhipster-dotnetcore pull request #1430
Opened 2023-12-09 08:18 UTC by JeSuisAlrick

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

2023-12-12 07:23 UTC, nicolas63 commented
Very nice work ! I will test it soon.  The sonar analysis is not a problem

2023-12-16 09:48 UTC, nicolas63 requested changes

2023-12-16 09:48 UTC, nicolas63 commented on generators/blazor/templates/src/client/Project.Client/Pages/Entities/_entityClass_/_entityClass_Detail.razor.ejs
> +@page "/<%= lowerCasedEntityClass %>/{Id<%_ if(isNumericPrimaryKey(primaryKeyType)) { %>:<%= primaryKeyType %> <%_ } _%> }/view"
here we need the id type like "{Id:guid}" without this the detail page can't convert the id

2023-12-16 09:48 UTC, nicolas63 commented on generators/blazor/templates/src/client/Project.Client/Pages/Entities/_entityClass_/_entityClass_Update.razor.ejs
> +@page "/<%= lowerCasedEntityClass %>/{Id<%_ if(isNumericPrimaryKey(primaryKeyType)) { %>:<%= primaryKeyType  %> <%_ } _%> }/edit"
Like the detailt page we need the id type here

2023-12-21 18:27 UTC, nicolas63 approved these changes
Everything looks good, if you agree, I can merge it.

2023-12-22 00:03 UTC, JeSuisAlrick commented
> Everything looks good, if you agree, I can merge it.

Yeah. I'm good with the changes.

I'm considering migrations as the next thing to work on, but I'll support this change.

2023-12-22 11:25 UTC, merged

2023-12-22 11:27 UTC, nicolas63 commented
Merged, thanks for your contribution