Fix pagination issue
jhipster/jhipster-dotnetcore pull request #514
Opened 2021-01-01 10:48 UTC by maznag

Fix #378.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

2021-01-01 21:15 UTC, nicolas63 requested changes

2021-01-01 21:15 UTC, nicolas63 commented on generators/server/templates/dotnetcore/src/Project/appsettings.json.ejs
> +            "EnforceHttps":  false
Mayve you can set EnforceHttps to false in https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/server/templates/dotnetcore/src/Project/appsettings.Development.json.ejs
and set to true in https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/server/templates/dotnetcore/src/Project/appsettings.Production.json.ejs

2021-01-05 20:08 UTC, nicolas63 approved these changes

2021-01-05 20:09 UTC, maznag commented
@nicolas63 @ivanmonteiro I propose to refactor `appsettings` and simplify security settings section as follow (remove jhipster key):

```
"Security": {
        "Authentication": {
            "Jwt": {
                "Base64Secret": "bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=",
                "TokenValidityInSeconds": 86400,
                "TokenValidityInSecondsForRememberMe": 2592000
            }
        },
        "Cors": {
            "AllowedOrigins": "*",
            "AllowedMethods": "*",
            "AllowedHeaders": "*",
            "ExposedHeaders": "Authorization,Link,X-Total-Count,X-Pagination",
            "AllowCredentials": true,
            "MaxAge": 1800
        },
        "EnforceHttps": false
    }
```

and 

```
public class SecuritySettings
    {
        public Authentication Authentication { get; set; }
        public Cors Cors { get; set; }
        public bool EnforceHttps { get; set; }
    }
```

What do you think ?

2021-01-05 20:14 UTC, nicolas63 commented
@maznag yes i think it's good idea
The build error is due to format error can you verify ?

2021-01-05 20:48 UTC, ivanmonteiro commented
> @nicolas63 @ivanmonteiro I propose to refactor `appsettings` and simplify security settings section as follow (remove jhipster key):
> 
> ```
> "Security": {
>         "Authentication": {
>             "Jwt": {
>                 "Base64Secret": "bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=",
>                 "TokenValidityInSeconds": 86400,
>                 "TokenValidityInSecondsForRememberMe": 2592000
>             }
>         },
>         "Cors": {
>             "AllowedOrigins": "*",
>             "AllowedMethods": "*",
>             "AllowedHeaders": "*",
>             "ExposedHeaders": "Authorization,Link,X-Total-Count,X-Pagination",
>             "AllowCredentials": true,
>             "MaxAge": 1800
>         },
>         "EnforceHttps": false
>     }
> ```
> 
> and
> 
> ```
> public class SecuritySettings
>     {
>         public Authentication Authentication { get; set; }
>         public Cors Cors { get; set; }
>         public bool EnforceHttps { get; set; }
>     }
> ```
> 
> What do you think ?

I agree with the change

2021-01-05 22:03 UTC, merged